spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
  application:
    name: weather-service
  profiles:
    active: ${PROFILE}